name: ${project.name}
main: com.spinalcraft.spinalpack.Spinalpack
version: ${project.version}

softdepend: [WorldGuard]

commands:
  rules:
    description: Get information about Spinalcraft's rules
    usage: Usage - /rules
    permission: spinalpack.rules
    permission-message: No!
  report:
    description: Report an issue to the mods
    usage: Usage - /report
    permission: spinalpack.report
    permission-message: No!
  setdonor:
    description: Give a user donor privileges
    usage: Usage - /setdonor <username>
    permission: spinalpack.setdonor
    permission-message: No!
  donate:
    description: Make a donation to Spinalcraft
    usage: Usage - /donate
    permission: spinalpack.donate
    permission-message: No!
  teamspeak:
    description: Join Spinalcrafts Teamspeak server
    usage: Usage - /teamspeak
    permission: spinalpack.teamspeak
    permission-message: No!
